### PR TITLE
Ready to Review - FrontEnd UI Navigation and Geo location

### PR DESCRIPTION
**Pull request by wzafar1**
Front End UI with Map Geo location and Home/location button configured

Still working on few Screens and small buys

### CODE REVIEW

**Comment by wzafar1** [comment]
All Conflicts fixed and code mergerd.

@coreyjjames I have moved the code that you had on home page to Tester (Located under More). Lets use that screen for testing separate from the main nav/app

**Review by kc-leung — CHANGES_REQUESTED** [review]
@wzafar1 that's not how you supposed to resolve the conflict cuz in this way you have removed some of the code from my previous pull request and probably Corey's ones as well. Making most of the thing I implemented unusable which I will have to re implement them again.

Resolving a conflict is not just as simple as keeping your current commits or incoming commits. It is to keep what is needed and what is not. So you should have keep your code and ours without breaking the application. That's why I was suggesting to resolve the conflict code together cuz this is a large Pull Request

Also, a way to avoid so many conflict codes at once  in the future is branching off from develop making sure it is up-to-date the code. I strongly advice you to branch off from develop for every new feature that you want to implement so we can avoid this issue. You just have to make sure to do a git pull before branching off from develop and you are good to go

I am gonna do a rebase of your branch and try to fix it

**Comment by wzafar1** [comment]
@kc-leung 
The reason for moving Corey code to Tester screen is we need to separate the home page from our tester code. nothing else was changed from his code and it works

Your code in the map was not removed but commented out with a note to link it with an icon since the current one only create red border around the screen

No other code was been changed

only the following files had a conflict
home, map, router.js

**Comment by wzafar1** [comment]
All components were tested after doing pull from develop and resolving the conflict

**Comment by kc-leung** [comment]
@wzafar1 
You just comented out the Redux functionality but you removed my logic implementation for the button and modalwindow in Map.js and its styling sheet please look closely.

**Comment by wzafar1** [comment]
@kc-leung 
Tester Page is for testing individual components which Corey had on the Home.js Page and they were moved to Tester.js Screen

No other Change were made to your codes. If you guys want me to delete your screen for individual component test then OK i will delete that instead of moving it to a seprate tester screen 

**Also, I have already added comment to your Code stating clearly that Icon will be added for test tasks.**
image

**Pull request closed without merging**
